# Generated by Django 3.2 on 2021-07-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210704_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postcommment',
            new_name='Postcomment',
        ),
    ]
