# Generated by Django 3.2 on 2021-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_postcommment_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
