# Generated by Django 3.2 on 2021-07-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210711_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.post'),
        ),
    ]
